### ISSUE TITLE
Ability to reverse https urls.

### ISSUE THREAD

**Issue by pipermerriam** [fusionbox/django-absoluteuri#1]
Looks like the protocol is currently hard coded as `http`

Would be nice to have this work with https

**Comment by rockymeza** [comment]
I agree.

The only way I was thinking that that could work is through a setting.

**Comment by pipermerriam** [comment]
I think a setting + an option in the function signature to allow specifying it on a per use basis.

**Comment by rockymeza** [comment]
the absoluteuri template tag wouldn't be able to accept the option, but I think everything else would work. I'm a little worried about the inconsistency there.
