### ISSUE TITLE
Release new version to PyPi

### ISSUE THREAD

**Issue by selectnull** [fusionbox/django-absoluteuri#5]
Hi,

as mentioned in comment https://github.com/fusionbox/django-absoluteuri/pull/4#issuecomment-130433926 , can you please release new version since there are no features in development.
It's much nicer to install from PyPi directly :)

Thanks.

**Comment by rockymeza** [comment]
ping @gavinwahl

**Comment by gavinwahl** [comment]
https://pypi.python.org/pypi/django-absoluteuri/1.2.0

**Comment by selectnull** [comment]
Thank you.
